### ISSUE TITLE
Should the code be ASCII only?

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1013]
On a recent discussion for the dev docs we talked about whether the current ASCII only rule could now be dropped (as for example the Windows console now correctly displays other characters).

https://github.com/Nemocas/Nemo.jl/pull/962

Should we retain the ASCII-only rule and add it to the conventions page of the developer docs? I support retaining the rule and know that @thofma does. Any objections?

There are currently non-ASCII chars in the partitions part of src/generic/GenericTypes.jl which would be affected by such a decision.

@kalmarek @fingolfin @fieker

**Comment by fingolfin** [comment]
Personally I have no problems with using unicode chars beyond ASCII (my Terminal and editors all support them just fine). That said, if they cause trouble for anybody, I fully supported upholding any existing rules against using them!

**Comment by fieker** [comment]
I'm also for banning non-ascii, at this point WSL has difficulties displaying them.
What are the advantages of allowing? Cool? Readablility?

**Comment by fieker** [comment]
we made the decision already a couple of times...

**Comment by wbhart** [comment]
WSL now displays them correctly. I am using the new version. But even so, if we still have devs on the old version, that's sufficient for me.

**Comment by wbhart** [comment]
Note that we would need to come up with a new notation for printed output of permutations.

**Comment by fieker** [comment]
On Mon, Mar 08, 2021 at 03:22:56AM -0800, wbhart wrote:
> WSL now displays them correctly. I am using the new version. But even so, if we still have devs on the old version, that's sufficient for me.

It
s more complicated. The problems are aparently only if you're using a
nno-english terminal (and the moon is nice, ...)

**Comment by wbhart** [comment]
Actually, maybe those actually are extended ASCII chars and I am confused. Perhaps @kalmarek can confirm.

**Comment by kalmarek** [comment]
I remember that the decision was to provide an AA/Oscar global switch for opting in/out of pretty printing. Did somebody implemented anything along these lines?

However, given that I've seen (or was not referenced) no such issues of such breakage in AA I understand this is no issue?

Otherwise feel free to alter code for showing Partitions/YoungTabs.

**Comment by wbhart** [comment]
@kalmarek Nothing breaks, it's just people can't read the chars on their terminal. This was definitely a problem with the old WSL.

I am not aware of any global switch being implemented. I'll look to see if there is a ticket and if not, add one.

**Comment by wbhart** [comment]
I opened an Oscar.jl ticket for it, but marked it as a decision, since it is not clear how to implement such a switch so that devs can read the code. Ideas are welcome on that ticket.

For now I will add the no-ASCII decision to the Nemo devel docs and close this when it's there.

**Comment by kalmarek** [comment]
@wbhart note that the code for showing partitions is 100% ASCII, UTF-8 symbols are only in console/doctests. At the price of readability you could do the same with `Generic._border` which is used for YoungTabs.

Also there is `Generic.setyoungtabstyle(::Symbol)` which accepts `:diagram` or `:array` to change that behaviour.

**Comment by wbhart** [comment]
@kalmarek I don't follow. Where is console/doctests?

Are you saying there is already an option somewhere to change the output printing of partitions? Or is this something we inherit from Julia or something?

**Comment by wbhart** [comment]
Oh sorry, I see it's not a path, LOL. I'm looking at the show code now.

**Comment by kalmarek** [comment]
Permutations/YoungTabs have function controlling their default show; Partitions don't; If you don't like `…` We can replace it via `Char(0x02026)`;
Subscripts are defined in `Generic/YoungTabs.jl` (this is path, :)

**Comment by wbhart** [comment]
We'd have to remove it altogether because the output has to be able to be displayed in the console.

**Comment by fingolfin** [comment]
On the risk of being hated upon: can someone (@fieker ?) specify where exactly these unicode chars fail? And how many of our developers are actually affected by this? How many of use develop on Windows using WSL (I think @fieker does, but who else?).

See, I don't mind going ASCII only, but if we start to revise working nice code, and also go against the general Julia trend (which seems to involve using lots of fancy Unicode stuff -- sometimes overdone), then shouldn't we at least be specific in our justification, and not just say that something once broke for something but we don't know the details? Also, if we record the details, then at least we can check in the future if the issue is still there.

**Comment by thofma** [comment]
First of all, I don't mind if the non-ASCII code we have at the moment stays or not. Mainly because I am not working on this part and @kalmarek was able to successfully sneak it in.

Regarding why not ASCII. There are lots of situations where one has to interact (read/write) with julia code outside of ones preferred setup. I don't have time to guess how to enter Unicode in ed/vim/nano/emacs on a server running an ancient CentOS when working remotely, or in the editor of choice of my coworker. Even if the display is correct, how do I enter it? (The is rhetorical. Please resist the urge to tell me how easy it is do to it in your setup.)

**Comment by wbhart** [comment]
As my proposed changes to the dev docs regarding banning non-ASCII are now merged, I am closing this issue.

Naturally it can be reopened at a later date if we decide that things have changed for all our devs.

Regarding the code that already uses non-ASCII, I will leave that ticket open, as I do not see a strong concensus on that. I am not in a hurry to change that code myself.
