### ISSUE TITLE
Solve benchmark is now nearly 10x slower

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#102]
The benchmark in solve_polynomials.jl (in the benchmark directory) now takes more than 50s, whereas we have it at 7s on our benchmark page. Reported by Bernard Parisse.

I checked out Nemo-0.4 and it completes in about 7s, but Nemo-0.5 takes more than 50s. The benchmark code is of course correct. I also compared Julia-0.4 and Julia-0.5 and only a very small amount of the regression is to do with that.

What I notice is that the memory usage has gone up from about 72Mb to 3.2Gb. This should be easy enough to track down with the Julia compiler's --track-allocations=all option.

**Comment by thofma** [comment]
I'll have a look tomorrow.

**Comment by wbhart** [comment]
Of course it is possible we weren't tracking all allocations back in Nemo-0.4, so maybe this will be a false lead.

**Comment by wbhart** [comment]
A manual git bisect might find the problem faster. Nothing needs to be recompiled each time (except Nemo itself), so this shouldn't be too hard to do.

**Comment by thofma** [comment]
Are we talking about the following function?
https://github.com/Nemocas/Nemo.jl/blob/master/benchmarks/polynomials_number_field.jl
Finishes in 0.1s on my machine with Nemo-0.5.2 and julia 0.5.0.

**Comment by thofma** [comment]
Regression happend between 487640e0250325f4bae7fdd10748b92a9aa0642c (good) and 66012c7d163e020f150ff0c334e21e64bf9b3207 (bad). Allocations went from 500 MB to over 3 GB. For example, https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/fmpz_poly.jl#L134 allocates
950 MB with the bad commit 66012c7d
2 MB with the good commit 487640e02
I haven't found the bug so far. There are some type instabilities, but nothing that has been introduced by 66012c7d. Any ideas?

P.S.: I am using julia 0.4.7.

**Comment by wbhart** [comment]
That's odd. I don't see any changes of any consequence between these two
commits. This is nothing more than a rename of the types, which shouldn't
affect anything.

**Comment by thofma** [comment]
Found it. In the bad commit, the signatures of the solve functions are
```julia
function solve{T <: RingElem}(M::MatElem{T}, b::MatElem{T})
function solve{T <: RingElem}(M::MatElem{PolyElem{T}}, b::MatElem{PolyElem{T}})
```
In the benchmark `M` and `b` are of type `MatElem{GenMat{fmpz_poly}}`. Although
```julia
julia> issubtype(GenPoly{fmpz_poly}, PolyElem{fmpz_poly})
true
```
we do have
```julia
julia> issubtype(MatElem{GenPoly{fmpz_poly}}, MatElem{PolyElem{fmpz_poly}})
false
```
because in julia type parameters are invariant. Thus julia uses the first method for `solve(M, b)` which does not try `solve_interpolation(M, b)` (`solve_interpolation(M, b)` gives the answer in ~6 seconds). By the way, in the bad commit, `solve_interpolation` can never be called.

We would need something like `{T <: RingElem, S <: MatElem{PolyElem{S}}}` in the signature(s), but julia does not have this triangular dispatch at the moment (they talk about it since 3 years but it has not been addressed so far).

I only see one solution. Change the signature(s) back to
```julia
function solve{T <: RingElem}(M::MatElem{GenPoly{T}}, b::MatElem{GenPoly{T}})
```
This will backfire once some implements e.g. some type
```julia
fast_bivariate_polys_over_Q <: PolyElem{fmpq_poly}
```
Then the function would not work for matrices of type `MatElem{fast_bivariate_polys_over_Q}`.

**Comment by wbhart** [comment]
This is essentially what I think solves the triangular dispatch problem, in
this case:

function solve{T <: PolyElem}(M::MatElem{T})
   # implementations for matrices over a polynomial ring
end

function solve_ring{T}(M:MatElem{T})
   # implementation for generic ring
end

function solve{T}(M::T)
   solve_ring(M)
end

We can put a comment in the source code that this hack can be removed once
Julia has triangular dispatch.

Bill.
