### ISSUE TITLE
Factorizing polynomial in F2

### ISSUE THREAD

**Issue by sorooshkhoram** [Nemocas/Nemo.jl#1024]
I have a matrix `T` with elements in F2 (`{0,1}`) and I want to factorize its characteristic polynomial.

`n = 3`
`F, x = FiniteField(2, n, "x")`

`T = [0.0 1.0 0.0; 1.0 0.0 1.0; 0.0 1.0 1.0]`
`T = matrix(F, Int.(T))`
`Zx, x = F["x"]`
 
`P = charpoly(Zx, T))`
`println(isirreducible(P))`
`println(P)`
`println(factor(P))`
 
This gives
> false
> x^3 + x^2 + 1
> 1 * (x + x^2 + 1) * (x + x^2 + x + 1) * (x + x + 1)

I'm not very well familiar with finite fields but the factorization seems incorrect and the `x^3+x^2+1` polynomial is irreducible. Am I doing this correctly?

**Comment by wbhart** [comment]
There's a couple of errors.

Firstly, FiniteField(2, n, "x") is F_{2^n} not F_2. If you want to do it like this, use FiniteField(2, 1, "x").

Secondly, you have used "x" twice, once for the finite field generator and once for the polynomials F["x"]. You should use a different variable and character for one of them, e.g. use Zy, y = F["y"].

For the finite field, you may as well use F = ResidueField(ZZ, 2) rather than F, x = FiniteField(2, 1, "x"). That way you don't need a generator for the finite field at all, since you are not using an extension of F_2 just F_2 itself.

Naturally you don't need to convert your matrix from a matrix of floats. You can just start with a matrix of integers to begin with. T = [0 1 0; 1 0 1; 0 1 1].

**Comment by wbhart** [comment]
By the way, congratulations on getting issue number 2^10 for a question about the finite field F_2.

**Comment by sorooshkhoram** [comment]
Thanks for the answer and the wit both worked
