### ISSUE TITLE
Nemo.numerator !== Nemo.AbstractAlgebra.numerator

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/Nemo.jl#1038]
and this is probably inconsistent? The full list looks like
```julia
julia> aa_names = names(Nemo.AbstractAlgebra, all=true, imported=true);

julia> nemo_names = names(Nemo, all=true, imported=true);

julia> for x in intersect(nemo_names, aa_names)
         a = @eval Nemo.$x
         b = @eval Nemo.AbstractAlgebra.$x
         if !(a===b)
           println(x)
         end
       end
##PolynomialRing#65
##meta#51
#1#2
#23#24
#3#5
#37#38
#4#6
#GF
#GF##kw
#NumberField
#NumberField##kw
#PolynomialRing#65
#eval
#include
#isprobable_prime
#test_module
#versioninfo
GF
NumberField
QQ
RealField
ZZ
denominator
eval
exp
include
inv
isprobable_prime
log
numerator
sqrt
test_module
versioninfo
```

**Comment by wbhart** [comment]
Thanks for the list. Here is the list of ones that look problematic to me.

```
denominator
isprobable_prime
numerator
```

Moreover, there may be issues wrt the following as we have our own internal definitions of these which don't match Base, but this is a separate issue which I believe already has a ticket
 
```
exp
inv
log
sqrt
```

**Comment by wbhart** [comment]
In the case of numerator and denominator, AbstractAlgebra does not import these from Base, which is a bug.

In the case of isprobable_prime, Nemo does not import this from AbstractAlgebra, which is a bug.

**Comment by wbhart** [comment]
In fact I am unable to find a ticket mentioning the issues with exp, inv, log and sqrt, so I will detail that here.

We provide our own versions of these (internal to Nemo) for fmpz and fmpq (which return results in the same ring). These are not exported to the user. This is all ok.

However, for Int and BigInt Nemo.blah will return the same thing as Base.blah, whereas AbstractAlgebra.blah does not. This is inconsistent and we should also make the AbstractAlgebra versions used internal to Nemo (but not exported therefrom).

**Comment by thofma** [comment]
`Nemo.exp === Base.exp`, so `exp(::fmpq)` is exported to the user. And I think it should be? Same for `inv`. Why would we not want to have `inv(::fmpq)` for users?

**Comment by wbhart** [comment]
Yes, you are correct. These *are* exported to the user, which is fine.

**Comment by thofma** [comment]
Thanks for checking. This always confuses me.

**Comment by wbhart** [comment]
Apparently we have our own version of numerator and denominator, so the fact that they don't equal the Base/Nemo version is intentional. However, perhaps it is still a bug that the Nemo version doesn't extend the AbstractAlgebra version instead of the Base version. The verdict on that score will probably be the same as for the other functions we define our own version of.

**Comment by thofma** [comment]
I have a feeling we just forgot to import it in AbstractAlgebra.

**Comment by wbhart** [comment]
No it is explicitly excluded from import with a comment in src/AbstractAlgebra.jl

**Comment by thofma** [comment]
I see. Then I think everything is fine. The comment says that any other package should not extend the AA version, but the Base version.

**Comment by wbhart** [comment]
Probably, but I'm going to look into this tomorrow, as I recall there was a problem with the internal definitions in Nemo, especially for Euclidean division. But I'm running out of steam for the day, so am not going to do that now. If all is ok, I'll close the ticket tomorrow.

**Comment by wbhart** [comment]
Ok, the original issue is an intentional behaviour so doesn't need fixing.

isprobable_prime is not exported from AbstractAlgebra which explains that issue. I've opened a PR for that.

The Nemo versions of div and divrem extend the AbstractAlgebra version not the Base version. This is probably so that the AbstractAlgebra versions can be used in Nemo itself.

The Nemo versions of inv, sqrt, log and exp extend the Base version, not the AbstractAlgebra version. At least sqrt and exp are in the import_exclude list and exp, log and sqrt are in the Base_import_exclude list in AbstractAlgebra. My guess is all four functions should be in both lists, but I'm not sure. Then Nemo should probably import the AbstractAlgebra ones for internal use, and overload the Base versions everywhere and not export the internal ones.

**Comment by wbhart** [comment]
I've added the functions that were missing in our special import/export exclude lists. There's still a question about whether Nemo should import the special version in each case for internal use (only). That seems to be the case already for div and divrem, but not for the others.

As it is unclear which way we should go, there is nothing further actionable here, so I will close the issue as resolved. We can revisit the issue later on if it starts to cause a problem for us (e.g. if more generic code is added to Nemo, warranting importing the special versions of these functions instead of the Base ones).
