### ISSUE TITLE
Document how to lift `gfp_elem`s

### ISSUE THREAD

**Issue by ssiccha** [Nemocas/Nemo.jl#1069]
IIRC one can access a representative of a `gfp_elem` `x` by doing `x.data`. Since there already is a `lift` function for polynomials, one could call that function `lift` too.

**Comment by ssiccha** [comment]
Hm, I sometimes have to do `mod(x.data, modulus)`.

**Comment by wbhart** [comment]
I suppose that if GF(p) is thought of as Z/pZ then it's a lift. I suppose it can't hurt. If no one really objects, we can do this, and also for ResidueRing(ZZ, n) of course.

**Comment by wbhart** [comment]
Currently I think ResidueField(ZZ, p) is different to GF(p) in Nemo (though less efficient I think). I don't remember why we did this. But at any rate it should also have a lift. Here it definitely makes sense to call it a lift.

**Comment by thofma** [comment]
I agree, we should have `lift(::gfp_elem)` yielding an `fmpz`. Maybe some `lift_raw` or whatever to get a `UInt`?

**Comment by wbhart** [comment]
We already have data(::gfp_elem) to return the UInt. This is documented here:

https://nemocas.github.io/AbstractAlgebra.jl/latest/residue_rings/

Granted that is hard to find. But until we completely rewrite the Nemo docs to include everything, instead of referring to AbstractAlgebra docs, I guess we are going to keep getting tickets like this.

However, I will implement the lift function for Z/nZ and GF(p) types, always returning an fmpz.
