### ISSUE TITLE
Rethink names for special functions

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#1073]
From #1071:

I am a little distraught at the arcane naming scheme for these functions.
Arbitrarily truncating `elliptic` to `ellip` or using `hyper` sometimes and
`hyp` sometimes is just bad style to me. Also, a nice cute name like `shi` is
really only cute for a few minutes. @fredrik-johansson
```
ei          => exp_integral_ei
si          => sin_integral
ci          => cos_integral
shi         => sinh_integral (or just omit this trivial function)
chi         => cosh_integral (ditto)
li          => log_integral
lioffset    => log_integral
expint      => exp_integral_e
hyp1f1      => hypergeometric_1f1
hyp1f1r     => hypergeometric_1f1_regularized
hyperu      => hypergeometric_u
hyp2f1      => hypergeometric_2f1
jtheta      => jacobi_theta
modeta      => modular_eta
modj        => modular_j
modlambda   => modular_lambda
moddelta    => modular_delta
ellipwp     => weierstrass_p
????        => weierstrass_p_prime
ellipk      => elliptic_k
ellipe      => elliptic_e
```

_Originally posted by @tthsqe12 in https://github.com/Nemocas/Nemo.jl/issues/1071#issuecomment-845745690_

**Comment by albinahlback** [comment]
Some more suggestions:
```
rgamma     -> reciprocal_gamma
lgamma     -> log_gamma
barnesg    -> barnes_g
logbarnesg -> log_barnes_g
erfi       -> erf_imaginary
erfc       -> erf_complementary
besselj    -> bessel_j (to be consistent with jacobi_theta)
bessely    -> bessel_y
besseli    -> bessel_i
besselk    -> bessel_k
```

But perhaps `erf_complementary` should be `complementary_erf` (and the same for `erf_imaginary`), in order to have the same style as the other ones. Then `hypergeometric_1f1_regularized` should probably be `regularized_hypergeometric_1f1`. Maybe this don't matter, I don't know.

**Comment by tthsqe12** [comment]
I not completely sure, but I think the abbreviations `erfc` and `erfi` are fairly standard (like `sin` and `sinh`).

**Comment by albinahlback** [comment]
How about `integral_sin` instead of `sin_integral` in order to classify the integral functions in a more apparent way (just like `modular_XXX` and `hypergeometric_XXX`)? Moreover, `sin_integral` can be read like _sine of some integral_ while `integral_sin` could be read like _integral of some sine function_. Opinions?

**Comment by fredrik-johansson** [comment]
See also: https://github.com/Nemocas/AbstractAlgebra.jl/issues/881
