### ISSUE TITLE
Nemo's FmpzModRing leaks and needs to be redesigned

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/Nemo.jl#1186]
The code that needs to be cleaned up is at the bottom. First, there is an inner constructor for `fmpz_mod_ctx_struct` that does nothing. Then, then `fmpz_mod_ctx_init` is not paired with a `fmpz_mod_ctx_clear` and in fact this latter function does not even appear in Nemo anywhere. Thus all of the moduli created are leaked.
https://github.com/Nemocas/Nemo.jl/blob/121cfabde4f6a7b4ebe706d47352ac6dc2f1d22b/src/flint/FlintTypes.jl#L465-L498

**Comment by wbhart** [comment]
The inner constructor for fmpz_mod_ctx_struct does nothing for two reasons:

1) The default inner constructor would take arguments for each of the fields in the fmpz_mod_ctx_struct and we want Flint to fill those, not Nemo.

2) We still need to allocate the space for the struct.

The lack of a finalizer is more concerning. But this may be due to the fact that finalizers can be called in any order and perhaps the finalizer for objects depending on an fmpz_mod_ctx_struct requires the struct to still exist when they are cleared.

I will try putting a finalizer in and see if the test code still passes. The alternative would be reference counting like we have in Singular.jl.
