### ISSUE TITLE
Latest docs are not

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#1188]
The "latest" docs are for an old version of Nemo:

http://nemocas.github.io/Nemo.jl/latest/

Compare with the latest version, which has the docs for Exact Real and Complex arithmetic for example.

**Comment by fingolfin** [comment]
I think `latest` was long ago deprecated by Documenter.jl -- there now is http://nemocas.github.io/Nemo.jl/dev/ and http://nemocas.github.io/Nemo.jl/stable/.  That it works at all (instead of giving a 404) is probably because nothing / nobody remove the `latest` dir or symlink from the `gh-pages` branch.

So, just remove that, and update all links to point to the "new" (relatively: they were around for at least 2 years, I think?) links
