### ISSUE TITLE
Don't extend Base methods on NTuples of Base types

### ISSUE THREAD

**Issue by tkelman** [Nemocas/Nemo.jl#141]
This is referred to as "type piracy" and strongly discouraged, as it changes the behavior of unrelated code depending on whether or not this package is imported. Specifically the methods on `NTuple{N, UInt}` at https://github.com/Nemocas/Nemo.jl/blob/9043252cc3eae14be4b9bd2ed89ad8a188047252/src/generic/MPoly.jl#L118-L152 would be better defined for a
package local wrapper type, as opposed to globally modifying Base method tables on Base types.

**Comment by wbhart** [comment]
Coincidentally I am currently rewriting this code. But I haven't found the
perfect solution yet. Performance is so critical here, and currently the
new solution is 20% slower (and still has some type piracy).

I have been experimenting with a multidimensional array, instead of an
array of NTuples. This should dramatically lower compilation times for us,
at least. But we are still losing on runtime performance due to the very
bad performance of Subarrays.

One of my colleagues is experimenting with a version of the Julia GC that
conservatively scans the stack, meaning the shadow stack can be turned off.
This might give us the flexibility we need, so that we can use "views"
instead of an NTuple type. But none of this solves the type piracy issue,
which I'm aware of.

**Comment by wbhart** [comment]
Actually, I think I can get rid of the type piracy, without losing any
further performance, without further degrading performance.

**Comment by thofma** [comment]
@tkelman Can we still tag a new version?

**Comment by tkelman** [comment]
Would be preferable to avoid globally modifying methods of a fundamental data type in ways that other code will notice.

**Comment by thofma** [comment]
Sure, we will address it at some point. But we need a new version now.

By the way, is there some official list of things one is not allowed to do in registered packages? When registering a package because a lecture is about to begin I do not want to find out that the unwritten rules have changed once more.

**Comment by tkelman** [comment]
Has been written down (there's now a style guide section specifically on type piracy), though should be put somewhere much easier to find: `https://github.com/JuliaLang/METADATA.jl/issues/6761#issuecomment-253893450`

**Comment by thofma** [comment]
Thanks, very useful but not that easy to find.

**Comment by tkelman** [comment]
Since tuples are used for argument lists in Julia., modifying methods on them can have some surprising consequences.
```
julia> a, b = UInt(1), UInt(2)
(0x0000000000000001, 0x0000000000000002)

julia> a, b *= 2
ERROR: MethodError: no method matching *(::Tuple{UInt64,UInt64}, ::Int64)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:424
  *(::Bool, ::T<:Number) where T<:Number at bool.jl:101
  *(::Complex{Bool}, ::Real) at complex.jl:244
  ...

julia> function Base.:*{N}(a::NTuple{N, UInt}, n::Int)
          return ntuple(i -> a[i]*reinterpret(UInt, n), Val{N})
       end

julia> a, b *= 2
(0x0000000000000002, 0x0000000000000004)
```

With a bit of creativity it's likely possible to come up a more harmful example, but even something like this toy example could hide bugs elsewhere depending only on whether or not this package is imported.

Depending how long you expect these tuples to be, you might be able to make use of the StaticArrays package to save some effort on this.

**Comment by tkelman** [comment]
In a local clone of master, it seems Nemo's tests still pass with the problematic lines 118-152 deleted, and nothing else changed. Are you sure those methods are needed in the current code? If so, what for?

**Comment by thofma** [comment]
The functionality is not covered by the tests.

**Comment by wbhart** [comment]
I expect to have the code rewritten within a couple of weeks. I have
managed to avoid the type piracy (by simply renaming the functions). I
don't need the operators any more. I'm still missing 20% of performance
with the new code, and I've given up trying to fix that. The new GC code
won't help with the 20% that's gone missing, but it should help close the
other factor of 4 difference to the C implementation.

The old code is actually really half-baked, and we merged it in way too
early. However, since we are going to need to have broken code like this
merged from time to time for classes and research, I suggest we discontinue
Nemo as an official package when we split it into Flint.jl and Nemo.jl.

**Comment by tkelman** [comment]
Looks like this was fixed by https://github.com/Nemocas/Nemo.jl/pull/143 ?

**Comment by thofma** [comment]
Yes. Does this mean I can try to tag a new version?

**Comment by tkelman** [comment]
Defining arithmetic methods on NTuple was the last objection I had, so yes.
