### ISSUE TITLE
Negative power gives wrong results in Nemo.GenRes{Nemo.fq_nmod_poly}

### ISSUE THREAD

**Issue by defeo** [Nemocas/Nemo.jl#151]
Reported by @erou

```
julia> using Nemo

julia> K, w = FiniteField(2, 2, "w")
(Finite field of degree 2 over F_2, w)

julia> R, T = K["T"]
(Univariate Polynomial Ring in T over Finite field of degree 2 over F_2,T)

julia> L = ResidueRing(R, T^2 + (w+1)*T + 1)
Residue ring of Univariate Polynomial Ring in T over Finite field of degree 2 over F_2 modulo T^2+(w+1)*T+(1)

julia> t = L(T)
T

julia> t^-1 == inv(t)
false

julia> t*t^-1
T
```

**Comment by defeo** [comment]
Tested in Julia 0.5.1, Nemo 0.5.1.

**Comment by wbhart** [comment]
It looks like on line 407 of flint/fq_poly.jl, it calls the powmod function
in Flint, which only supports nonnegative exponents. This can be fixed in
Nemo itself by dealing specially with negative exponents (in fq_poly.jl,
fq_nmod_poly.jl, and probably nmod_poly.jl and fmpz_mod_poly.jl), or by
fixing Flint to do the same.

If I find time and a decent internet connection I'll do this. Or maybe
@thofma is able to.

**Comment by thofma** [comment]
@wbhart Do you prefer the flint fix?

**Comment by wbhart** [comment]
I don't mind too much. I don't have a strong preference either way.
