### ISSUE TITLE
Consistent indendation in Nemo

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#1751]
I think it is somewhat annoying that Nemo does not use a consistent indentation throughout the project. Could we agree on one specific indentation, and push that throughout the project?

**Comment by lgoettgens** [comment]
We already added a `.editorconfig` and a `JuliaFormatter.toml` in https://github.com/Nemocas/Nemo.jl/pull/1698. But pushing this through may create a lot of conflicts with open PRs. But since there are not many left and all of them are from people we know, we could do that in the near future. What do you think @fingolfin @thofma ?
