### ISSUE TITLE
FlintZZ doesn't work in benchmark code

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#25]
If we change ZZ -> FlintZZ in the pearce and minpoly_gcd_domain benchmarks, it fails.

This occurs in Rings.jl where for some reason it doesn't recognise the runtime generated promote_rules. This seems like it could be a bug in Julia.

**Comment by thofma** [comment]
Which julia version?

**Comment by thofma** [comment]
I cannot confirm that it works with `ZZ` in place of `FlintZZ`. The line
https://github.com/Nemocas/Nemo.jl/blob/master/src/generic/Poly.jl#L1749
is the problem, since one cannot iterate over an object of type `MethodTable`. Did it work before with some julia version?

Also Nemo tests are failing on my machine due to this function. This is strange since travis is passing on 0.5: https://travis-ci.org/Nemocas/Nemo.jl/jobs/131336295

By the way, this is my julia version:
```
julia> versioninfo()                                               
Julia Version 0.5.0-dev+3789                                       
Commit e7dc4a4 (2016-04-29 06:59 UTC)                              
Platform Info:                                                     
  System: Linux (x86_64-linux-gnu)                                 
  CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz             
  WORD_SIZE: 64                                                    
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Nehalem) 
  LAPACK: libopenblas64_                                           
  LIBM: libopenlibm                                                
  LLVM: libLLVM-3.7.1 (ORCJIT, nehalem)                            
```

**Comment by wbhart** [comment]
My Julia is about 14 days old. They changed how this works. You have to
update your Julia.

**Comment by thofma** [comment]
Fixed.
