### ISSUE TITLE
Bugs due to new generic stuff

### ISSUE THREAD

**Issue by thofma** [Nemocas/Nemo.jl#263]
It seems that lots of ad hoc functions have been removed from the flint wrappers leading to bugs:
```julia
julia> Qx, x = PolynomialRing(FlintQQ, "x")
(Univariate Polynomial Ring in x over Rational Field, x)

julia> x//2
1/2*x

julia> typeof(ans)
Nemo.GenFrac{Nemo.fmpq_poly}
```
It should be `fmpq_poly`.

**Comment by wbhart** [comment]
They weren't removed, it's just that they were defined in the wrong place.
They are now inside the Generic module (inside Fraction.jl), which means
that they no longer apply to Flint types. I'll move them out to Fields.jl.

**Comment by thofma** [comment]
Huh? They should be in Generic, since we don't have a place where all the abstract stuff go.

It is the special method `//(::PolyElem{T}, ::Rational) where T <: FieldElem`, why should it go into Fields.jl?

**Comment by thofma** [comment]
And ofcourse only for fields of characteristic 0.

**Comment by wbhart** [comment]
We are talking about different functions. The functions I was talking about
were:

**Comment by wbhart** [comment]
Another GMail bug. And they only just fixed the CTRL-S one!

The functions I was talking about were:

//(x::T, y::Union{Integer, Rational}) where {T <: RingElem} =
x//parent(x)(y)

//(x::Union{Integer, Rational}, y::T) where {T <: RingElem} =
parent(y)(x)//y

These only operate if parent(y)(x) makes sense, which is in turn only
defined for char 0 fields, of course.

Those functions clearly shouldn't be inside Generic, and especially not in
Fraction.jl, because they don't apply to Fractions.

Hmm, actually fixing this didn't seem to fix the problem. I'm
investigating....

**Comment by wbhart** [comment]
Ok, what should the following give:

R, x = PolynomialRing(ZZ, "x")

f = x//2

??

**Comment by thofma** [comment]
GenFrac{fmpz_poly}?

**Comment by wbhart** [comment]
And how do I do:

R, x = PolynomialRing(QQ, "x")

and create the object

x/2 in Frac(QQ[x])?

Clearly x//2 should create the latter.

**Comment by wbhart** [comment]
So, in fact, this is not a bug. When you do R, x = PolynomialRing(QQ, "x")
you are creating a ring, not a field. Therefore x//2 has to create an
object in GenFrac{fmpq_poly}, not an object in fmpq_poly. So it was correct
how it was.

If you want x/2 in fmpq_poly, you have to do divexact(x, 2).

**Comment by thofma** [comment]
No, this is not how it used to be. I did not know that you changed functionality. There is no rule that // must create objects in the fractiona field. If the types allow for the result to stay in the ring, why shouldn't it give a result in the ring?

**Comment by wbhart** [comment]
It's always been the intention that // creates objects in the fraction
field unless the numerator and denominator are in the same field.

Unlike QQ, the ring QQ[x] is not a field. It's a ring. Therefore, // can
have only one meaning.

I'm not sure which function you want defined. Can you give the prototype.
It's hard to come up with an example that fails without a specific proposal.

I can't define //(a::PolyElem, b::Integer) = divexact(a, b) since then x//2
fails in Z[x].

I can't define //(a::PolyElem, b::Integer) to apply // pointwise on the
coefficients of a, since again, x//2 will fail in Z[x].

And I can't define //(a::PolyElem{T}, b::Integer) where T <: FieldElem,
since it will then fail over Generic.Poly{fmpq_poly}.

So I don't see a workable way of making things work the way you want. The
function // has always been intended to return an element of the fraction
field of an integral domain, unless it happens to already be a field, in
which case it becomes an exact division in the field.
