### ISSUE TITLE
Feature request: nearby_rational

### ISSUE THREAD

**Issue by heiderich** [Nemocas/Nemo.jl#450]
I would welcome a function like `nearby_rational` in Sage (see page 24 in http://doc.sagemath.org/pdf/en/reference/rings_numerical/rings_numerical.pdf). I think it could take elements of type Nemo.arb as input (plus something like `max_denominator` or `max_error`) and output elements of type `Nemo.fmpq`. Does this make sense?

**Comment by wbhart** [comment]
I think it makes sense. Perhaps @fredrik-johansson has a suggestion?

**Comment by thofma** [comment]
I have hacked something together in Hecke using the continued fraction functionality from flint, but it is quite fragile. Would love to have something fast and more robust in Nemo.

**Comment by fredrik-johansson** [comment]
Yes, it makes sense. The logical interface would be to return the simplest rational contained inside the given arb_t.

The easiest way to implement this would be via a function that returns the simplest rational in [a,b] for two fmpq a, b. With an arb_t input, it's then just a matter of doing an exact conversion to an fmpq pair. 

I would not mind putting a robust implementation of this feature in Arb itself.

There does need to be some kind of bound for both the numerator and denominator when going from an arb_t since the exponents could be large.

**Comment by thofma** [comment]
@tthsqe12

**Comment by thofma** [comment]
I am not an expert but this looks fine to me.

**Comment by tthsqe12** [comment]
@thofma I think we are near to closing this issue. Since fredrik seems to be MIA for a robust implementation in arb, you will have to do one last step yourself. very rough psuedo code:
```
simplest_inside(arb_t x):
    fmpz_t a, b, d, e
    fmpq_t r
    arb_get_interval_fmpz_2exp(a, b, e, x)
    e = -e
    do something special if e does not fit in a ulong
    d = 2^e
    _fmpq_simplest_between(numref(r), denref(r), a, d, b, d)
   return r
```

**Comment by thofma** [comment]
OK, so the things are merged in flint?

**Comment by tthsqe12** [comment]
@thofma could we get an update on where your stuff is/what it is called and possibly close this?

**Comment by thofma** [comment]
Will do.
