### ISSUE TITLE
Request advice (Julia 0.6 versus Julia 1.0)

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#492]
This function works with Julia 0.6.4:

    function Divisors(n::Int, dosort=false)
        n == fmpz(0) && return fmpz[]
        Nemo.isprime(fmpz(n)) && return [fmpz(1), n]
        d = [fmpz(1)]
        for (p, e) in Nemo.factor(fmpz(n))
            c = [p^i for i in 0:e]
            d = d * c'
            d = reshape(d, length(d))
        end
        dosort && sort!(d)
        d
    end
    println(Divisors(391))

However with Julia 1.0.1 the following error occurs:

    LinearAlgebra.Adjoint{Any,Array{Nemo.fmpz,1}}
    ERROR: LoadError: MethodError: no method matching adjoint(::Nemo.fmpz)
    Closest candidates are:
      adjoint(::Missing) at missing.jl:79
      adjoint(::Number) at number.jl:193
      adjoint(::LinearAlgebra.Adjoint) at C:\Users\julia\AppData\Local\Julia- 
      1.0.1\share\julia\stdlib\v1.0\LinearAlgebra\src\adjtrans.jl:104

Any advice? Thanks!

**Comment by wbhart** [comment]
It's the ' used for transpose causing the problem. In Julia 1 this changed to a lazy adjoint. Try transpose or something like that (I actually forget what the exact function is).

**Comment by thofma** [comment]
I agree that this is quite confusing. There are basically three operations: `adjoint` (same as `'`), `transpose` and `permutedims`. The first two are recursive and return a lazy object. Because they are recursive, `adjoint` needs `adjoint(::fmpz)` to be defined. On the other hand, `permutedims` will work for any 2-dimensional array containing any objects, since it is not recursive.

So at the moment your two options are:
```julia
julia> fmpz[1, 2] * transpose(fmpz[1, 2])
2×2 Array{fmpz,2}:
 1  2
 2  4

julia> fmpz[1, 2] * permutedims(fmpz[1, 2])
2×2 Array{fmpz,2}:
 1  2
 2  4
```
To make `'` work again, we should do `adjoint(x::RingElem) = x` as the fallback and `adjoint(x::acb) = conj(x)`.
