### ISSUE TITLE
(::AbstractAlgebra.Integers{BigInt})(::fmpz)

### ISSUE THREAD

**Issue by heiderich** [Nemocas/Nemo.jl#521]
It is currently not possible to coerce integers of type fmpz into AbstractAlgebra.ZZ:

```
julia> AbstractAlgebra.ZZ( one(Nemo.ZZ) )
ERROR: MethodError: no method matching (::AbstractAlgebra.Integers{BigInt})(::fmpz)
```

I would welcome such a feature.

**Comment by wbhart** [comment]
There is convert(BigInt, fmpz(1))

I think this is the better way to do this, because converting everything back to Julia is not something that is super useful once you have Nemo. It just encourages everyone to think they should do everything via Julia BigInts, which makes for some pretty inefficient code.

**Comment by heiderich** [comment]
Thanks. The actual motivation was #522. Probably it would be fine to use `convert` in that situation.
