### ISSUE TITLE
factor takes longer than expected

### ISSUE THREAD

**Issue by OpenLibMathSeq** [Nemocas/Nemo.jl#607]
Consider Bnum(n) = numerator(abs(bernoulli(2*n))).
SageMath immediately returns for  

    factor(Bnum(48)) 
    7823741903 * 4155593423131 * 10017952436526113 
    * 96454277809515481 * 6735480167773644873691271

After waiting for more than 5 minutes Nemo version 0.13.3 
with Julia-1.3.0-DEV has not returned.

**Comment by wbhart** [comment]
They might be caching the factorisations, or maybe it is just that they have a good factoring implementation. We have a quadratic sieve for large factorisations and this would not factor this number. You need the elliptic curve method for that. We have it implemented, but not hooked up, because the implementation has never been tuned.

**Comment by thofma** [comment]
We have a factor version with ecm and caching at https://github.com/thofma/Hecke.jl/blob/f3a2f3e35c76630d5a64d006d2e82495a6a74120/src/Misc/Integer.jl#L793
Feel free to copy it. I don't have access to a computer at the moment, so I cannot try it with your example myself.

**Comment by OpenLibMathSeq** [comment]
Thank you very much! I will try this.

**Comment by wbhart** [comment]
This takes a couple of seconds in Nemo now, which seems reasonable.
