### ISSUE TITLE
Segfault in FiniteField constructor with bad base ring

### ISSUE THREAD

**Issue by Keno** [Nemocas/Nemo.jl#667]
I typo'd the ResidueRing (1 instead of 2) and the subsequent `FiniteField` constructor segfaulted.
```
julia> R, x= ResidueRing(ZZ,1)["x"]
(Univariate Polynomial Ring in x over Integers modulo 1, 0)

julia> F = FiniteField(R(x^3+x^2+1), "z")

signal (11): Segmentation fault: 11
in expression starting at REPL[16]:1
fq_nmod_ctx_init_modulus at /Users/kfischer/.julia/dev/Nemo/deps/usr/lib/libflint.dylib (unknown line)
FqNmodFiniteField at /Users/kfischer/.julia/dev/Nemo/src/flint/FlintTypes.jl:1557
```

**Comment by wbhart** [comment]
The solution I would implement is to prevent people from using ResidueRings instead of GF(p) for the base field. But if I do that, someone will complain.

If I try to fix this any other way, I am either duplicating code or checking for primality twice.

Unless everyone agrees to only allow GF(p) or ResidueField as the coefficient field, I'd prefer to just leave this bug as it is. Unfortunately, you are unlikely to get agreement on this though.

**Comment by rfourquet** [comment]
If we keep allowing a `ResidueField`, I think we should not segfault, and primality should be checked. I'm not sure why primality would have to be checked twice in this case, but I say it's worth it to avoid a very user-unfriendly segfault. It wouldn't affect the "recommended" use-cases were `GF(p)` is used.

**Comment by wbhart** [comment]
@rfourquet You aren't going to prevent this problem unless you disallow ResidueRing for constructing finite fields, or unless you check primality when constructing the extension but only when ResidueRing is used and not ResidueField.

I'm always reluctant to implement fixes like this, as the correct fix is clearly to disallow ResidueRing being used in the first place. That's the whole reason we introduced ResidueField.

**Comment by rfourquet** [comment]
> unless you check primality when constructing the extension but only when ResidueRing is used and not ResidueField.

Yes, this is what I had in mind. So yes, if a `ResidueRing` is used multiple times to construct a `FiniteField`, with the same base ring, then indeed primality will be checked twice, by default. 

I don't have a strong opinion on removing altogether the functionality. But we do already something like that for matrices: algorithms which require a square matrix work both on `MatAlgElem` and `MatElem`, for convenience, with a check for squareness (which is no-op on `MatAlgElem`). This is for convenience, in order to smooth out the rigidity imposed by the type system (i.e. if I end up with a `ResidueRing(ZZ, 3)`, this models a field, even if the type system doesn't know it).
