### ISSUE TITLE
Welcome message

### ISSUE THREAD

**Issue by lairez** [Nemocas/Nemo.jl#817]
First of all, thanks for your work on Nemo, very useful to me!

I am annoyed by the welcome message. It is a bit intrusive (it is the only Julia package I know that does this) and it also appear when Nemo is loaded as a dependency so it may not be relevant at all for the user. And you already know that this is an issue because there is a special condition to disable the welcome message when Nemo is loaded from Oscar or Hecke ;)

Could you please remove this welcome message?

**Comment by stevengj** [comment]
I agree that this is a bit unusual.   As a workaround, [it looks like](https://github.com/Nemocas/Nemo.jl/blob/ea2e6539431b11f0688d34629063fe6a06e837d6/src/Nemo.jl#L258-L267) you can set `ENV["NEMO_PRINT_BANNER"] = "false"` to suppress the message.

**Comment by wbhart** [comment]
Nemo is a computer algebra system that uses various LGPL 2+ libraries. As such we consider Nemo to be adding an interactive interface to those libraries. Condition 2(c) of GPL v2 requires such banners when such interactive interfaces are added.

As mentioned above, the banner can be suppressed when using Nemo as a library in a program which does not add an interactive interface to any of those libraries.

**Comment by fredrik-johansson** [comment]
As far as I can tell this requirement does not appear in the LGPL.

**Comment by thofma** [comment]
I agree with @fredrik-johansson.

**Comment by wbhart** [comment]
Oh dear, let's not start this again. The GPL conditions are part of the LGPL.

**Comment by wbhart** [comment]
Sorry, you are right, the LGPL v2.1 is a distinct license, not a set of exceptions to the GPL.

**Comment by wbhart** [comment]
Yeah, my mistake. The issue is that GMP is LGPL v3+ (or GPL v2) which means that overall Nemo is LGPL v3+. Thus the LGPL for us is a set of exceptions to the GPL v3.

Therefore section 5(d) applies. This is not one of the excepted sections in the LGPL v3.

Sorry for getting this around the wrong way above.

**Comment by Krastanov** [comment]
FYI, for other people that end up on this discussion from an internet search: For many tasks you might need to import just the `AbstractAlgebra` library instead of the entire `Nemo`. This is an explicitly non-interactive piece of code, so the whole conversation about what the GPL does and does not say is side-stepped.

**Comment by jtrakk** [comment]
If the [`Logging`](https://docs.julialang.org/en/v1/stdlib/Logging/) module is used instead of printing to stdout, users could customize the behavior to their liking generically instead of needing to specifically handle this module.
