### ISSUE TITLE
Constructing a Rational Nemo matrix doesn't work

### ISSUE THREAD

**Issue by cossio** [Nemocas/Nemo.jl#82]
Why:

`Nemo.MatrixSpace(Nemo.QQ, 3, 4)(fill(1//2, 3, 4))`

doesn't work? I expect this to return a matrix over the rationals.

**Comment by wbhart** [comment]
We apparently haven't written a constructor to convert a matrix of Julia
Rational{Int}'s to Nemo.QQ's. Thanks for reporting this.

This works though:

 MatrixSpace(QQ, 3, 4)(fill(QQ(1, 2), 3, 4))

or

 MatrixSpace(QQ, 3, 4)(fill(ZZ(1)//2, 3, 4))

We probably should overload fill so it works with Nemo types, and similarly
we probably should make QQ(1//2) work.

Bill.

**Comment by cossio** [comment]
@wbhart Thanks for the reply. Something like this to get started?

```
Base.convert(::Type{Nemo.fmpq}, x::Rational) = Nemo.QQ(x.num, x.den)
Base.call(::Nemo.FlintRationalField, x::Rational) = Nemo.QQ(x.num, x.den)
```

I would do a PR, but I don't know where to place this.

**Comment by wbhart** [comment]
This would probably go in Nemo/src/flint/fmpq.jl towards the end of the
file with the other "call" functions.

The convert function could go in the section on promotions very nearby. We
don't have many of these because mostly convert can't be used with Nemo
types. This happens to be a rare exception.

In library code you want to use fmpq(x.num, x.den) instead of QQ(x.num,
x.den). It may be faster.

Also, there's no need to qualify everything with Nemo inside the Nemo
module.

Bill.

**Comment by thofma** [comment]
This works now.
