### ISSUE TITLE
Return pivot indices from rref

### ISSUE THREAD

**Issue by cossio** [Nemocas/Nemo.jl#83]
Currently `rref` only returns the matrix in reduced row echelon form. It would be useful if the pivot indices that were used were returned as well.

**Comment by wbhart** [comment]
We would have to change the interface of the Flint functions that do rref
in order to accommodate this.

I think the only way to do it would be to implement a new function
rref_with_transform, both for all the Flint rings that implement rref and
also in the generic Matrix module in Julia. This could be useful for some
applications (presumably).

I note for example that Sage and Julia do not return a transformation
matrix. Magma does. Probably the best situation would be to have both
possibilities.

When working over a ring, Magma returns the Hermite Normal Form when doing
EchelonForm, and we do have a hnf_with_transform function already, so at
least this part of the job is already done.

However, currently rref for a matrix over Z doesn't return the HNF in Nemo,
but it does quasi-rref, i.e. thinks of the entries as lying in the fraction
field. This is mainly used for actually computing the rref over the
fraction field, so it is more useful as an internal function than as an end
user thing.

As for just returning the pivots, I am not sure of the applications versus
returning a transformation matrix. Do you have a specific use case in mind?

Bill.

**Comment by thofma** [comment]
I like the idea of introducing `rref_with_transform`. It would be very valuable.

**Comment by thofma** [comment]
Let's put `rref_with_transform` on the todo list.
