### ISSUE TITLE
mpoly missing/extra functions

### ISSUE THREAD

**Issue by tthsqe12** [Nemocas/Nemo.jl#840]
As far as I can tell `push_term!(a::{nmod|fmpz|fmpq}_mpoly, coeff, exps)` are not calling the corresponding function in flint.
Also, `nmod_mpoly_integral` https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/nmod_mpoly.jl#L589 does not exist, Should it?

**Comment by thofma** [comment]
> As far as I can tell `push_term!(a::{nmod|fmpz|fmpq}_mpoly, coeff, exps)` are not calling the corresponding function in flint.

I don't think we have `push_term!` functionality for any multivariate polynomial at all. There is this `MPolyBuildCtx` in AbstractAlgebra. Do you mean that those do not use flint functions where they should?

> Also, `nmod_mpoly_integral` https://github.com/Nemocas/Nemo.jl/blob/master/src/flint/nmod_mpoly.jl#L589 does not exist, Should it?

Would be nice if exists. But I guess it is too late for that.

**Comment by tthsqe12** [comment]
1) Yes, they are not using the flint functions.
2) Why is it too late?

**Comment by thofma** [comment]
Because, there is already an alpha for the new flint release? I thought this could be a problem.

I guess it should do a similar thing as `nmod_poly_integral`. On the other hand, we don't have an integral function for the generic multivariate implementation in AbstractAlgebra. So maybe we actually don't want one? @wbhart

**Comment by tthsqe12** [comment]
Yes, I meant push_term! for the corresponding builder context.

**Comment by thofma** [comment]
Yeah, we can change that.

PS.: Did you get my messages regarding the printing?
