### ISSUE TITLE
problem with non-square linear equation systems

### ISSUE THREAD

**Issue by ThomasBreuer** [Nemocas/Nemo.jl#887]
Nemo's `solve` can solve non-square linear equation systems over `ZZ` but not over `QQ`.
```
julia> using Nemo

Welcome to Nemo version 0.18.1

Nemo comes with absolutely no warranty whatsoever


julia> m1 = [ 1 1 ; 1 0; 1 0 ]; m1Z = matrix(ZZ, m1); m1Q = matrix(QQ, m1);

julia> m2 = [ 1 0 ; 0 1; 0 1 ]; m2Z = matrix(ZZ, m2); m2Q = matrix(QQ, m2);

julia> solve(m1Z, m2Z)
[0   1]
[1  -1]

julia> solve(m1Q, m2Q)
ERROR: Not a square matrix in solve
```

**Comment by wbhart** [comment]
We are aware of this problem and I actually plan to work on the linear algebra, especially for non-square systems immediately after I finish the work on number field sqrt. It's rather involved to fix unfortunately, so it will take some weeks of work.

**Comment by wbhart** [comment]
@ThomasBreuer Although we still have a fair bit of work to do in order to get a fast result, you can now at least solve non-square systems using base case generic solve as follows:

```
julia> m1 = [ 1 1 ; 1 0; 1 0 ]; m1Z = matrix(ZZ, m1); m1Q = matrix(QQ, m1);

julia> m2 = [ 1 0 ; 0 1; 0 1 ]; m2Z = matrix(ZZ, m2); m2Q = matrix(QQ, m2);

julia> flag, X = can_solve_with_solution(m1Z, m2Z)

julia> flag, X = can_solve_with_solution(m1Q, m2Q)
```

Some faster algorithms in the case of fraction fields will be available with the next release of AbstractAlgebra. I am working on even faster methods in Flint right now and I'll let you know once those become available. They will eventually be available in Nemo.
