### ISSUE TITLE
rref over Z returns arguments in different order to AbstractAlgebra

### ISSUE THREAD

**Issue by wbhart** [Nemocas/Nemo.jl#899]
AbstractAlgebra returns r, d, A, Nemo returns r, A, d

**Comment by rfourquet** [comment]
Are we sure we prefer fixing Nemo than AA here? I didn't think much about it, but Nemo's convention seems preferable to me here: for a field, you get `(r, A)`, for a ring you get `(r, A, d)`, so in all cases the second element is a matrix. We could even unify both by returning `(r, A, 1)` in the field case, so that in all cases, `(r, A, d) = rref(...); isrref(A/d) == true`, even if `d == 1`. This might not even be much breaking, as you can still do `r, A0 = rref(...)` and the third returned value will be ignored.
(Not saying this is a very strong argument, but as one of Nemo or AA must be changed... )

**Comment by thofma** [comment]
I agree with @rfourquet on this one.

**Comment by wbhart** [comment]
This has been dealt with in AbstractAlgebra.
