### ISSUE TITLE
lll timings

### ISSUE THREAD

**Issue by fieker** [Nemocas/Nemo.jl#946]
I have an explicit matrix A. Consider the timings:

julia> @time lll(A);
 84.504325 seconds (8.39 M allocations: 285.933 MiB, 0.01% gc time)

julia> @time lll(lll(A, lll_ctx(0.75, 0.51)));
 24.665416 seconds (2.57 M allocations: 178.778 MiB, 0.01% gc time)

the runtimes for lll_with_removal are even worse than lll (when the bound is large enough to be non-trivial), so I suggest
- change the default value for the lll_ctx to be the original lll values (0.75, 0.51)
- implement lll with the current parameters by first reducing with the courser parameters

My understanding from discussions with Damien Stehle is that this behaviour is actually expected.
Note that FPLLL is about the same speed as flint (here) while Magma is 20% faster

I wil try to attach the matrix as an includeable Nemo-file... for github reasons it is badA.log
[badA.log](https://github.com/Nemocas/Nemo.jl/files/5780485/badA.log)

**Comment by fieker** [comment]
Note this lattice come from factoring polynomials using the knacpsack/ van Hoeij approach. Replacing with_removal by with_removal_knapsack made thigs even worse....

**Comment by fieker** [comment]
pari is also on 60sec

**Comment by thofma** [comment]
Those parameters where chosen when @wbhart wrapped the lll calls. Maybe the strategy of first going via the original lll values (0.75, 0.51) is not always the best strategy? Would be good to hear what @wbhart thinks.

**Comment by fieker** [comment]
On Thu, Jan 07, 2021 at 04:04:04AM -0800, thofma wrote:
> Those parameters where chosen when @wbhart wrapped the lll calls. Maybe the strategy of first going via the original lll values (0.75, 0.51) is not always the best strategy? Would be good to hear what @wbhart thinks.
> 
Its not always the best, in particular when lll is (very) cheap, this
harms.

Even more interesting is lll_with_removal: this seems to be either fast
or helped a lot by 1st calling lll without removal. If fast, it can hurt
really badly to call lll first, if slow, it can be 10x faster to reduce
1st, in particular, cascading with different parameters.

I discussed this briefly with Dan and he suspects that the case of large
matrices with small entries (here 60 bits) is not handled optimally...

**Comment by wbhart** [comment]
We really can't adjust parameters based on a single example. Obviously how long LLL takes depends on the actual arithmetic content of the vectors.

**Comment by wbhart** [comment]
I suggest that for examples like this you wrap the full Flint interface to LLL and set the parameters yourself to ones that are suitable for your particular problem.

**Comment by wbhart** [comment]
I don't recall exactly why we choose the parameters we do, but they are from memory ones that are for factoring polynomials over Z. They should be the same ones we used in Flint 1, which were set very deliberately to those values by Andy Novocin.

**Comment by wbhart** [comment]
One thing we could do is try these changes in Flint itself, where there is a standard suite of polynomial factorisation benchmarks. (It's not on by default, since it takes ages to run, but there's a flag in the test code you can enable to run it.) If the timings improve overall without slowing down any of the longer running tests substantially, then that would make a case for the changes.

**Comment by fieker** [comment]
There are different issues at hand:
- document and discuss that in some/many instances the default paramters are bad, as this gives a start for improvements.
- discuss default paramters and strategies: to me, personally, I'd rather set the defaults as in LLL82 as this is THE reference. If for some applications other settings and strategies are better, so be it. Note: I do not argue/ ask for a change
- we have the complete interface wrapped - which is frequently useful
- setting defaults based on a single application is also possibly not optimal
However, the main purpose is to start discussions based on real examples. I am happy to provide more "log" files, the one above is by no means the worst....

**Comment by CarloSircana** [comment]
I don't know if this comment will be helpful, but I've played with this so I want to share my feelings.
In my experience, increasing the parameters gradually helps a lot in the big examples (where "big" means large entries or high dimension). So we should probably search for a "threshold" to understand when to use the multiple calls with increasing parameters and when to call directly the lll, otherwise the easy cases will get much slower.
I want to point out that the runtime is not a matter of "original" parameters: for difficult examples the best solution seems to be first to compute the lll with small parameter (0.35, 0.51), then increase them to the "original" parameters and finally with the default parameters (0.99, 0.51).

**Comment by wbhart** [comment]
We do not implement the original LLL85 hence we do not use the parameters suggested for it (which are not justified anyway). Instead we use the parameters suggested for the L^2 algorithm.

It makes no sense to go back to the original parameters unless you can justify it with a range of benchmarks. The parameters we have used here were picked with a range of benchmarks in mind, albeit for an implementation of van Hoeij-Novocin, which this isn't quite (it should be close in performance though).

The fact that you can find large example for which changing the LLL parameters or strategy speeds it up doesn't surprise me in the slightest. There are standard examples for which screwing with LLL will dramatically slow one down and speed the other up.

But anecdotes are not data. Let's see some systematic benchmarks with different kinds of polynomials.

**Comment by thofma** [comment]
Why should we look at polynomials? We are talking about the LLL parameters for Nemo, which is used not only for polynomial factorization.

**Comment by thofma** [comment]
Sorry, I understand. I think we are talking now about a different strategy in flint itself.

**Comment by wbhart** [comment]
A benchmark across numerous applications would be even better. Though one of the LLL's is mainly for factorisation, so that one should use polynomials.

Anyhow, with regard to parameters I refer you to Damien Stehle's article in the LLL book in which he explains that due to the approximations used in floating point LLL's the original LLL parameters are not suitable. In the section "A thoughtful wrapper" he justifies why one wants to use the parameters usually chosen for his algorithm.

**Comment by wbhart** [comment]
Note that in flint2/trunk in fmpz_lll/test there is a test function t-wrapper which could be used as the starting point for a benchmark for LLL. It doesn't contain tests for all types of LLL problems that Flint can generate and it has been cut down dramatically to fit the time requirements for tests that are regularly run, but it's a start at least.

**Comment by fieker** [comment]
Not stateing that Wikipedia is THE reference, but how do I see the
defintion used in the implementation and how to I get the corresponding
properties
 - bound on the 1st basis vector relative to the minimum
 - bound on the 1st basis vector relative to discriminant
 - bound on the product of the basis vectors (orthogonality defect)?
or at least one should add a sentence like:
  choosing ... one obtains the original parameters.

The justification of the original parameters was to obtain a nice
presentation.

**Comment by wbhart** [comment]
I think this is an issue you should take up with Damien.

He says in his paper the original parameters do not work with his algorithm
and explains why. The LLL book gives answers to your other questions in
sections on alpha reduced LLL bases.
