### ISSUE TITLE
Provide more documentation for well-used functions

### ISSUE THREAD

**Issue by albinahlback** [Nemocas/Nemo.jl#953]
Some functions like `nullspace` don't have any documentation.

During the summer when I was introduced to Nemo.jl, I felt like there was alot of well-used functions that didn't have any documentation. I will try to see what I felt was missing, and complement documentation for theses functions.

**Comment by thofma** [comment]
Hm, I think `?nullspace` is printing two docstrings that should be relevant to your application.

Most of the functions are already documented here: https://nemocas.github.io/AbstractAlgebra.jl/latest/matrix/, because they work for any matrix in the ecosystem. So there is no separate documentation for e.g. nullspace of `fmpq_mat`. There is actually a link at https://nemocas.github.io/Nemo.jl/latest/matrix.html#Matrix-functionality-1. Maybe we should link directly link to https://nemocas.github.io/AbstractAlgebra.jl/latest/matrix/#Matrix-functionality-provided-by-AbstractAlgebra.jl?

We appreciate any feedback you can provide to improve the documentation.

**Comment by albinahlback** [comment]
> Hm, I think ?nullspace is printing two docstrings that should be relevant to your application.

Yes, you're right. I should have tested that before posted, as well as understood more about Nemo extending AbstractAlgebra.

> There is actually a link at https://nemocas.github.io/Nemo.jl/latest/matrix.html#Matrix-functionality-1. Maybe we should link directly link to https://nemocas.github.io/AbstractAlgebra.jl/latest/matrix/#Matrix-functionality-provided-by-AbstractAlgebra.jl?

I think that's a good idea!

When searching in Nemo's online documentation, would it be possible to extend the search for some certain subsections of AbstractAlgebra? So if I would search for `nullspace`, I would also get a result that links me to `https://nemocas.github.io/AbstractAlgebra.jl/latest/matrix/#Nullspace`.
