### ISSUE TITLE
inv fails for nmod_mat

### ISSUE THREAD

**Issue by simonbrandhorst** [Nemocas/Nemo.jl#956]
```
julia> R = ResidueRing(ZZ,9)
julia> G = matrix(R,2,2,[2,1,1,2])
[2  1]
[1  2]
julia> inv(G)
Flint exception (Impossible inverse):
    Cannot invert modulo 2*0
ERROR: Problem in the Flint-Subsystem
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] flint_abort() at .../.julia/packages/Nemo/mmz6V/src/Nemo.jl:118
 [3] inv(::nmod_mat) at .../.julia/packages/Nemo/mmz6V/src/flint/nmod_mat.jl:443
 [4] top-level scope at REPL[303]:1
```
It appears also for other residue rings
```
julia> R = ResidueRing(ZZ,9)
Integers modulo 9julia> G = matrix(R,2,2,[3,1,1,3])
[3  1]
[1  3]
julia> inv(G)
Flint exception (Impossible inverse):
    Cannot invert modulo 3*0
ERROR: Problem in the Flint-Subsystem

```
As far as I can tell the problem occurs when the entry at [1,1] is not invertible.

**Comment by wbhart** [comment]
For the moment, this is behaving essentially as intended. It tries to apply
the standard algorithms for inverting a matrix, but if it encounters an
impossible inverse, it fails.

Making all our functions work for Z/nZ is a major undertaking, and in some
cases we do not even have algorithms for it.

If this is particularly urgent for some project you are working on, let us
know and we can prioritise it. But it's not a trivial fix so will take some
time either way.

**Comment by thofma** [comment]
We are running into this quite often in our group in Saarbrücken. I don't think that this behavior is intended. If an element is invertible, `inv` should compute its inverse and not throw an error (which is useless for users). It has been over 2 years since Thomas raised the issue here https://github.com/Nemocas/Nemo.jl/issues/504. I will prepare a PR to fix it by computing the inverse of `Z`.
